insert into public.places (name, address, neighborhood, borough, style, barstool_score, tier) values
  ('Di Fara Pizza',              '1424 Avenue J',              'Midwood',           'Brooklyn',      'NY Classic',   9.4, 1),
  ('Lucali',                     '575 Henry St',               'Carroll Gardens',   'Brooklyn',      'Neapolitan',   9.3, 1),
  ('Ceres',                      '141 Mulberry St',            'Little Italy',      'Manhattan',     'NY Artisan',   9.2, 1),
  ('Lazzara''s Pizza',           '221 W 38th St',              'Midtown',           'Manhattan',     'NY Thin',      9.3, 1),
  ('L''Industrie',               '254 S 2nd St',               'Williamsburg',      'Brooklyn',      'NY Italian',   8.9, 1),
  ('Scarr''s Pizza',             '22 Orchard St',              'Lower East Side',   'Manhattan',     'NY Classic',   8.7, 1),
  ('Prince Street Pizza',        '27 Prince St',               'SoHo',              'Manhattan',     'Sicilian',     8.6, 1),
  ('John''s of Bleecker Street', '278 Bleecker St',            'West Village',      'Manhattan',     'Coal-fired',   8.8, 1),
  ('Una Pizza Napoletana',       '175 Orchard St',             'Lower East Side',   'Manhattan',     'Neapolitan',   8.7, 1),
  ('Joe''s Pizza',               '7 Carmine St',               'West Village',      'Manhattan',     'NY Classic',   8.4, 1),
  ('Rubirosa',                   '235 Mulberry St',            'Nolita',            'Manhattan',     'NY Thin',      8.5, 1),
  ('Mama''s Too',                '2750 Broadway',              'Upper West Side',   'Manhattan',     'Sicilian',     8.5, 1),
  ('Patsy''s Pizzeria',          '2287 1st Ave',               'East Harlem',       'Manhattan',     'Coal-fired',   8.3, 1),
  ('Keste Pizza and Vino',       '271 Bleecker St',            'West Village',      'Manhattan',     'Neapolitan',   8.4, 1),
  ('Motorino',                   '349 E 12th St',              'East Village',      'Manhattan',     'Neapolitan',   8.3, 1),
  ('Lombardi''s',                '32 Spring St',               'Nolita',            'Manhattan',     'Coal-fired',   8.0, 1),
  ('Roberta''s',                 '261 Moore St',               'Bushwick',          'Brooklyn',      'Wood-fired',   8.3, 1),
  ('Paulie Gee''s Slice Shop',   '110 Franklin St',            'Greenpoint',        'Brooklyn',      'NY Slice',     8.4, 1),
  ('Best Pizza',                 '33 Havemeyer St',            'Williamsburg',      'Brooklyn',      'NY Classic',   8.2, 1),
  ('L&B Spumoni Gardens',        '2725 86th St',               'Gravesend',         'Brooklyn',      'Sicilian',     8.6, 1),
  ('Totonno''s',                 '1524 Neptune Ave',           'Coney Island',      'Brooklyn',      'Coal-fired',   8.4, 1),
  ('Juliana''s',                 '19 Old Fulton St',           'DUMBO',             'Brooklyn',      'Coal-fired',   8.3, 1),
  ('Louie and Ernie''s',         '1300 Crosby Ave',            'Schuylerville',     'Bronx',         'NY Classic',   8.7, 1),
  ('Patsy''s Pizzeria Original', '2287 Arthur Ave',            'East Tremont',      'Bronx',         'Coal-fired',   8.5, 1),
  ('Zero Otto Nove',             '2357 Arthur Ave',            'Belmont',           'Bronx',         'Neapolitan',   8.2, 1),
  ('New Park Pizza',             '156-71 Cross Bay Blvd',      'Howard Beach',      'Queens',        'NY Classic',   8.5, 1),
  ('Nick''s Pizza',              '108-26 Ascan Ave',           'Forest Hills',      'Queens',        'NY Coal',      8.4, 1),
  ('Joe and Pat''s',             '1758 Victory Blvd',          'Castleton Corners', 'Staten Island', 'NY Thin',      8.2, 1),
  ('Denino''s',                  '524 Port Richmond Ave',      'Port Richmond',     'Staten Island', 'NY Classic',   8.3, 1),
  ('Lee''s Tavern',              '60 Hancock St',              'Dongan Hills',      'Staten Island', 'NY Classic',   8.1, 1);
